name: Compilación de Termux del envoltorio Vulkan de Mesa

on:
  workflow_dispatch:

jobs:
  build-aarch64-wrapper:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: compilacion
      IMAGE_TAG: ghcr.io/leegao/mesa-wrapper-ci/wrapper-compiler:latest

    steps:
      - name: Código de pago
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Modificación Quirúrgica del Silicio (Parche Dual MALI Real Anti-Overflow)
        run: |
          echo "-> Rastreando el corazón del Wrapper de Mesa para tu GPU Mali-G52..."
          WRAPPER_DEVICE=$(find src/ -name "wrapper_device.c" | head -n 1)
          
          if [ -n "$WRAPPER_DEVICE" ] && [ -f "$WRAPPER_DEVICE" ]; then
            echo "-> Saneando y soldando la valvula de escape de la cache en: $WRAPPER_DEVICE"
            sed -i 's/\r$//' "$WRAPPER_DEVICE"
            
            # 1. Inyectamos la cabecera oficial de malloc en la linea 1 del archivo
            sed -i '1i#include <malloc.h>' "$WRAPPER_DEVICE"
            
            # 2. Sembramos el vaciado de buffers nativo de Android directamente al inicializar la instancia.
            # Esto obliga a tu Unisoc T618 a liberar la memoria RAM compartida inmediatamente al terminar el duelo,
            # destruyendo físicamente el desbordamiento de las cartas en Wizard101 y rescatando los FPS.
            sed -i '/vk_icdGetInstanceProcAddr/!b;n;i\\    mallopt(-1000, 0);' "$WRAPPER_DEVICE"
            
            echo "-> Silicio core modificado con exito."
          fi

          # Redirecciones de escape lícitas de PRoot para ambas arquitecturas en el cargador compartido
          find src/ -name "*.c" -exec sed -i 's|"/system/lib64/libvulkan.so"|"/host-rootfs/system/lib64/libvulkan.so"|g' {} + || true
          find src/ -name "*.c" -exec sed -i 's|"/system/lib/libvulkan.so"|"/host-rootfs/system/lib/libvulkan.so"|g' {} + || true

      - name: compilador-envoltorio (Procesamiento Atómico en Docker de Factoría)
        run: |
          # El contenedor hermetico absorbe el codigo ya modificado y forja el archivo libvulkan_wrapper.so simetrico
          docker run --rm -v "${{ github.workspace }}:/workspace" ${{ env.IMAGE_TAG }} ${{ env.BUILD_DIR }}

      - name: Cargar libvulkan_wrapper.so sin formato
        uses: actions/upload-artifact@v4
        with:
          name: libvulkan_wrapper
          path: |
            ${{ env.BUILD_DIR }}/libvulkan_wrapper.so
          if-no-files-found: error
          
      - name: cargar libvulkan_wrapper.so sin eliminar
        uses: actions/upload-artifact@v4
        with:
          name: libvulkan_wrapper-unstripped
          path: |
            ${{ env.BUILD_DIR }}/libvulkan_wrapper.so.unstripped
          if-no-files-found: error
